### ISSUE TITLE
This no longer works?

### ISSUE THREAD

**Issue by mflaxman** [adamisntdead/medium-toc#2]
It appears medium has changed their format and it's no longer compatible with having a ToC, which is a major bummer.

![Screen Shot 2019-07-11 at 6 00 45 PM](https://user-images.githubusercontent.com/448644/61090898-d3fee580-a405-11e9-840f-bfef27fea355.png)

**Comment by adamisntdead** [comment]
Thanks for letting me know, I will have a look in a few hours on how to update for the new style.
Great to here that you're using it!

**Comment by mflaxman** [comment]
Btw, it appears they now have a `name` attribute (I believe you were using id) which can be used. Here's a really hackey/manul gist I put together that works for now:
https://gist.github.com/mflaxman/46d1124e09b0c01eedc6affd058130f9

**Comment by adamisntdead** [comment]
Sorry it has taken so long, I have updated it. Your code was very helpful, thanks so much.
